// <auto-generated />
using System;
using FACLSchichtbericht.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FACLSchichtbericht.Migrations.FACL_DB_Production
{
    [DbContext(typeof(FACL_DB_ProductionContext))]
    [Migration("20210530220108_Addberichte")]
    partial class Addberichte
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FACLSchichtbericht.Models.ActiontrackerModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Action")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bereich")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BerichtBD420_ID")
                        .HasColumnType("int");

                    b.Property<int?>("BerichtBD451_ID")
                        .HasColumnType("int");

                    b.Property<int?>("BerichtBU320_ID")
                        .HasColumnType("int");

                    b.Property<int?>("BerichtBU420_ID")
                        .HasColumnType("int");

                    b.Property<string>("Beschreibung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<string>("Maßnahme")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Overview_ID")
                        .HasColumnType("int");

                    b.Property<string>("Priorität")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Von")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("erstelltam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("erstelltvon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("istabgeschlossen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("zuletztbearbeitetam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("zuletztbearbeitetvon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Actiontracker");
                });

            modelBuilder.Entity("FACLSchichtbericht.Models.BerichtBD420Model", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AbfertigerIst")
                        .HasColumnType("int");

                    b.Property<int?>("AbfertigerKrank")
                        .HasColumnType("int");

                    b.Property<int?>("AbfertigerSoll")
                        .HasColumnType("int");

                    b.Property<int?>("AbfertigerZusatz")
                        .HasColumnType("int");

                    b.Property<string>("Arbeitunsfall")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AufbauerIst")
                        .HasColumnType("int");

                    b.Property<int?>("AufbauerKrank")
                        .HasColumnType("int");

                    b.Property<int?>("AufbauerSoll")
                        .HasColumnType("int");

                    b.Property<int?>("AufbauerZusatz")
                        .HasColumnType("int");

                    b.Property<int?>("AwaitingBulk")
                        .HasColumnType("int");

                    b.Property<int?>("AwaitingBulkFast")
                        .HasColumnType("int");

                    b.Property<int?>("AwaitingLCC")
                        .HasColumnType("int");

                    b.Property<int?>("AwaitingLCCFast")
                        .HasColumnType("int");

                    b.Property<int?>("BDStartBulk")
                        .HasColumnType("int");

                    b.Property<int?>("BDStartBulkFast")
                        .HasColumnType("int");

                    b.Property<int?>("BDStartLCC")
                        .HasColumnType("int");

                    b.Property<int?>("BDStartLCCFast")
                        .HasColumnType("int");

                    b.Property<decimal?>("BulkMengeMaStunden")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("BulkMengeMenge")
                        .HasColumnType("int");

                    b.Property<decimal?>("BulkMengeProdu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("CDSDGR")
                        .HasColumnType("int");

                    b.Property<int?>("CDSStandard")
                        .HasColumnType("int");

                    b.Property<int?>("CheckerIst")
                        .HasColumnType("int");

                    b.Property<int?>("CheckerKrank")
                        .HasColumnType("int");

                    b.Property<int?>("CheckerSoll")
                        .HasColumnType("int");

                    b.Property<int?>("CheckerZusatz")
                        .HasColumnType("int");

                    b.Property<int?>("HalBulk")
                        .HasColumnType("int");

                    b.Property<int?>("HalBulkFast")
                        .HasColumnType("int");

                    b.Property<int?>("HalLCC")
                        .HasColumnType("int");

                    b.Property<int?>("HalLCCFast")
                        .HasColumnType("int");

                    b.Property<int?>("Leihscanner")
                        .HasColumnType("int");

                    b.Property<int?>("Leihstapler")
                        .HasColumnType("int");

                    b.Property<int?>("PbEiBulk")
                        .HasColumnType("int");

                    b.Property<int?>("PbEiLCC")
                        .HasColumnType("int");

                    b.Property<int?>("PbEiLoco")
                        .HasColumnType("int");

                    b.Property<int?>("PbMiBulk")
                        .HasColumnType("int");

                    b.Property<int?>("PbMiLCC")
                        .HasColumnType("int");

                    b.Property<int?>("PbMiLoco")
                        .HasColumnType("int");

                    b.Property<int?>("Pending")
                        .HasColumnType("int");

                    b.Property<int?>("PendingBulk")
                        .HasColumnType("int");

                    b.Property<int?>("PendingBulkFast")
                        .HasColumnType("int");

                    b.Property<int?>("PendingLCCFast")
                        .HasColumnType("int");

                    b.Property<int?>("SupervisorIst")
                        .HasColumnType("int");

                    b.Property<int?>("SupervisorKrank")
                        .HasColumnType("int");

                    b.Property<int?>("SupervisorSoll")
                        .HasColumnType("int");

                    b.Property<int?>("SupervisorZusatz")
                        .HasColumnType("int");

                    b.Property<int?>("ULDKG")
                        .HasColumnType("int");

                    b.Property<decimal?>("ULDKGMAStunden")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ULDKGProdu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ULDMengeMAStunden")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ULDMengeMenge")
                        .HasColumnType("int");

                    b.Property<decimal?>("ULDMengeProdu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("abgeschlossenam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("abgeschlossenvon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("erstelltam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("erstelltvon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("freigegebenam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("freigegebenvon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("istabgeschlossen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("istfreigegeben")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("schichtbeginn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("schichtbeurteilung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("schichtdatum")
                        .HasColumnType("datetime2");

                    b.Property<string>("schichtende")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("schichttyp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("zuletztbearbeitetam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("zuletztbearbeitetvon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("BerichtBD420");
                });

            modelBuilder.Entity("FACLSchichtbericht.Models.BerichtBD437Model", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("ID");

                    b.ToTable("BerichtBD437");
                });

            modelBuilder.Entity("FACLSchichtbericht.Models.BerichtBD451Model", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AbfertigerIst")
                        .HasColumnType("int");

                    b.Property<int?>("AbfertigerKrank")
                        .HasColumnType("int");

                    b.Property<int?>("AbfertigerSoll")
                        .HasColumnType("int");

                    b.Property<int?>("AbfertigerZusatz")
                        .HasColumnType("int");

                    b.Property<string>("Arbeitunsfall")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AufbauerIst")
                        .HasColumnType("int");

                    b.Property<int?>("AufbauerKrank")
                        .HasColumnType("int");

                    b.Property<int?>("AufbauerSoll")
                        .HasColumnType("int");

                    b.Property<int?>("AufbauerZusatz")
                        .HasColumnType("int");

                    b.Property<int?>("AwaitingLoco")
                        .HasColumnType("int");

                    b.Property<int?>("BDStartLoco")
                        .HasColumnType("int");

                    b.Property<int?>("CDSDGR")
                        .HasColumnType("int");

                    b.Property<int?>("CDSStandard")
                        .HasColumnType("int");

                    b.Property<int?>("CheckerIst")
                        .HasColumnType("int");

                    b.Property<int?>("CheckerKrank")
                        .HasColumnType("int");

                    b.Property<int?>("CheckerSoll")
                        .HasColumnType("int");

                    b.Property<int?>("CheckerZusatz")
                        .HasColumnType("int");

                    b.Property<int?>("HalLoco")
                        .HasColumnType("int");

                    b.Property<int?>("Leihscanner")
                        .HasColumnType("int");

                    b.Property<int?>("Leihstapler")
                        .HasColumnType("int");

                    b.Property<int?>("PendingLoco")
                        .HasColumnType("int");

                    b.Property<int?>("SupervisorIst")
                        .HasColumnType("int");

                    b.Property<int?>("SupervisorKrank")
                        .HasColumnType("int");

                    b.Property<int?>("SupervisorSoll")
                        .HasColumnType("int");

                    b.Property<int?>("SupervisorZusatz")
                        .HasColumnType("int");

                    b.Property<int?>("ULDKG")
                        .HasColumnType("int");

                    b.Property<decimal?>("ULDKGMAStunden")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ULDKGProdu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ULDMengeMAStunden")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ULDMengeMenge")
                        .HasColumnType("int");

                    b.Property<decimal?>("ULDMengeProdu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("abgeschlossenam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("abgeschlossenvon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("erstelltam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("erstelltvon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("freigegebenam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("freigegebenvon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("istabgeschlossen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("istfreigegeben")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("schichtbeginn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("schichtbeurteilung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("schichtdatum")
                        .HasColumnType("datetime2");

                    b.Property<string>("schichtende")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("schichttyp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("zuletztbearbeitetam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("zuletztbearbeitetvon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("BerichtBD451");
                });

            modelBuilder.Entity("FACLSchichtbericht.Models.BerichtBU320Model", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AKHKG")
                        .HasColumnType("int");

                    b.Property<decimal?>("AKHKGMAStunden")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AKHKGProdu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("AbfertigerIst")
                        .HasColumnType("int");

                    b.Property<int?>("AbfertigerKrank")
                        .HasColumnType("int");

                    b.Property<int?>("AbfertigerSoll")
                        .HasColumnType("int");

                    b.Property<int?>("AbfertigerZusatz")
                        .HasColumnType("int");

                    b.Property<string>("Arbeitunsfall")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("BellyMengeMAStunden")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("BellyMengeMenge")
                        .HasColumnType("int");

                    b.Property<decimal?>("BellyMengeProdu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("CDSDGR")
                        .HasColumnType("int");

                    b.Property<int?>("CDSStandard")
                        .HasColumnType("int");

                    b.Property<int?>("Leihscanner")
                        .HasColumnType("int");

                    b.Property<int?>("Leihstapler")
                        .HasColumnType("int");

                    b.Property<int?>("PalettiererIst")
                        .HasColumnType("int");

                    b.Property<int?>("PalettiererKrank")
                        .HasColumnType("int");

                    b.Property<int?>("PalettiererSoll")
                        .HasColumnType("int");

                    b.Property<int?>("PalettiererZusatz")
                        .HasColumnType("int");

                    b.Property<int?>("SupervisorIst")
                        .HasColumnType("int");

                    b.Property<int?>("SupervisorKrank")
                        .HasColumnType("int");

                    b.Property<int?>("SupervisorSoll")
                        .HasColumnType("int");

                    b.Property<int?>("SupervisorZusatz")
                        .HasColumnType("int");

                    b.Property<int?>("TeamleadIst")
                        .HasColumnType("int");

                    b.Property<int?>("TeamleadKrank")
                        .HasColumnType("int");

                    b.Property<int?>("TeamleadSoll")
                        .HasColumnType("int");

                    b.Property<int?>("TeamleadZusatz")
                        .HasColumnType("int");

                    b.Property<decimal?>("ULDMengeMAStunden")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ULDMengeMenge")
                        .HasColumnType("int");

                    b.Property<decimal?>("ULDMengeProdu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("abgeschlossenam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("abgeschlossenvon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("erstelltam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("erstelltvon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("freigegebenam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("freigegebenvon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("istabgeschlossen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("istfreigegeben")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("schichtbeginn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("schichtbeurteilung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("schichtdatum")
                        .HasColumnType("datetime2");

                    b.Property<string>("schichtende")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("schichttyp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("zuletztbearbeitetam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("zuletztbearbeitetvon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("BerichtBU320");
                });

            modelBuilder.Entity("FACLSchichtbericht.Models.BerichtBU420Model", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AbfertigerIst")
                        .HasColumnType("int");

                    b.Property<int?>("AbfertigerKrank")
                        .HasColumnType("int");

                    b.Property<int?>("AbfertigerSoll")
                        .HasColumnType("int");

                    b.Property<int?>("AbfertigerZusatz")
                        .HasColumnType("int");

                    b.Property<string>("Arbeitunsfall")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CDSDGR")
                        .HasColumnType("int");

                    b.Property<int?>("CDSStandard")
                        .HasColumnType("int");

                    b.Property<int?>("Leihscanner")
                        .HasColumnType("int");

                    b.Property<int?>("Leihstapler")
                        .HasColumnType("int");

                    b.Property<int?>("PalettiererIst")
                        .HasColumnType("int");

                    b.Property<int?>("PalettiererKrank")
                        .HasColumnType("int");

                    b.Property<int?>("PalettiererSoll")
                        .HasColumnType("int");

                    b.Property<int?>("PalettiererZusatz")
                        .HasColumnType("int");

                    b.Property<int?>("SupervisorIst")
                        .HasColumnType("int");

                    b.Property<int?>("SupervisorKrank")
                        .HasColumnType("int");

                    b.Property<int?>("SupervisorSoll")
                        .HasColumnType("int");

                    b.Property<int?>("SupervisorZusatz")
                        .HasColumnType("int");

                    b.Property<int?>("TeamleadIst")
                        .HasColumnType("int");

                    b.Property<int?>("TeamleadKrank")
                        .HasColumnType("int");

                    b.Property<int?>("TeamleadSoll")
                        .HasColumnType("int");

                    b.Property<int?>("TeamleadZusatz")
                        .HasColumnType("int");

                    b.Property<int?>("ULDKG")
                        .HasColumnType("int");

                    b.Property<decimal?>("ULDKGMAStunden")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ULDKGProdu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ULDMengeMAStunden")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ULDMengeMenge")
                        .HasColumnType("int");

                    b.Property<decimal?>("ULDMengeProdu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("abgeschlossenam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("abgeschlossenvon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("erstelltam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("erstelltvon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("freigegebenam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("freigegebenvon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("istabgeschlossen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("istfreigegeben")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("schichtbeginn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("schichtbeurteilung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("schichtdatum")
                        .HasColumnType("datetime2");

                    b.Property<string>("schichtende")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("schichttyp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("zuletztbearbeitetam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("zuletztbearbeitetvon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("BerichtBU420");
                });

            modelBuilder.Entity("FACLSchichtbericht.Models.BerichtBU437Model", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("ID");

                    b.ToTable("BerichtBU437");
                });

            modelBuilder.Entity("FACLSchichtbericht.Models.BerichtTransportModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("ID");

                    b.ToTable("BerichtTransport");
                });

            modelBuilder.Entity("FACLSchichtbericht.Models.DateiModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Abgeschlossenam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Abgeschlossenvon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("Base64")
                        .HasColumnType("bigint");

                    b.Property<string>("Endung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Erstelltam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Erstelltvon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Freigegebenam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Freigegebenvon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IstFreigegeben")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Istabgeschlossen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kategorie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Datei");
                });

            modelBuilder.Entity("FACLSchichtbericht.Models.DropdownoptionsModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Optionbezeichnung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Selectbezeichnung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("value")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Dropdownoptions");
                });

            modelBuilder.Entity("FACLSchichtbericht.Models.FlugleistungenModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("ID");

                    b.ToTable("Flugleistungen");
                });

            modelBuilder.Entity("FACLSchichtbericht.Models.FlugplanModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DIR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DepDateLtFRA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Destination")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dienstleister")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Endetime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Flugnummer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Indikator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Palettierplatz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlatzOffnungvorSTD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Startime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("USG13")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Weekday")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Flugplan");
                });

            modelBuilder.Entity("FACLSchichtbericht.Models.OverviewModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ArbeitsunfallBD420")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArbeitsunfallBD437")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArbeitsunfallBD451")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArbeitsunfallBU320")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArbeitsunfallBU420")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArbeitsunfallBU437")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BD420BULKMengeMenge")
                        .HasColumnType("int");

                    b.Property<decimal?>("BD420BulkMengeProdu")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal?>("BD420BulkMengeStunden")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<int?>("BD420ULDKGMenge")
                        .HasColumnType("int");

                    b.Property<decimal?>("BD420ULDKGProdu")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal?>("BD420ULDKGStunden")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<int?>("BD420ULDMengeMenge")
                        .HasColumnType("int");

                    b.Property<decimal?>("BD420ULDMengeProdu")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal?>("BD420ULDMengeStunden")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<int?>("BD437ULDKGMenge")
                        .HasColumnType("int");

                    b.Property<decimal?>("BD437ULDKGProdu")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal?>("BD437ULDKGStunden")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<int?>("BD437ULDMengeMenge")
                        .HasColumnType("int");

                    b.Property<decimal?>("BD437ULDMengeProdu")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal?>("BD437ULDMengeStunden")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<int?>("BD451ULDKGMenge")
                        .HasColumnType("int");

                    b.Property<decimal?>("BD451ULDKGProdu")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal?>("BD451ULDKGStunden")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<int?>("BD451ULDMengeMenge")
                        .HasColumnType("int");

                    b.Property<decimal?>("BD451ULDMengeProdu")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal?>("BD451ULDMengeStunden")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<int?>("BDAbfertigerIst")
                        .HasColumnType("int");

                    b.Property<int?>("BDAbfertigerKrank")
                        .HasColumnType("int");

                    b.Property<int?>("BDAbfertigerSoll")
                        .HasColumnType("int");

                    b.Property<decimal?>("BDAbfertigerZusatz")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<int?>("BDAufbauerIst")
                        .HasColumnType("int");

                    b.Property<int?>("BDAufbauerKrank")
                        .HasColumnType("int");

                    b.Property<int?>("BDAufbauerSoll")
                        .HasColumnType("int");

                    b.Property<decimal?>("BDAufbauerZusatz")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<int?>("BDCheckerIst")
                        .HasColumnType("int");

                    b.Property<int?>("BDCheckerKrank")
                        .HasColumnType("int");

                    b.Property<int?>("BDCheckerSoll")
                        .HasColumnType("int");

                    b.Property<decimal?>("BDCheckerZusatz")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<int?>("BDSupervisorIst")
                        .HasColumnType("int");

                    b.Property<int?>("BDSupervisorKrank")
                        .HasColumnType("int");

                    b.Property<int?>("BDSupervisorSoll")
                        .HasColumnType("int");

                    b.Property<decimal?>("BDSupervisorZusatz")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<int?>("BU320AKHKGMenge")
                        .HasColumnType("int");

                    b.Property<decimal?>("BU320AKHKGProdu")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal?>("BU320AKHKGStunden")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<int?>("BU320AKHMengeMenge")
                        .HasColumnType("int");

                    b.Property<decimal?>("BU320AKHMengeProdu")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal?>("BU320AKHMengeStunden")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<int?>("BU320BellyMengeMenge")
                        .HasColumnType("int");

                    b.Property<decimal?>("BU320BellyMengeProdu")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal?>("BU320BellyMengeStunden")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<int?>("BU420ULDKGMenge")
                        .HasColumnType("int");

                    b.Property<decimal?>("BU420ULDKGProdu")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal?>("BU420ULDKGStunden")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<int?>("BU420ULDMengeMenge")
                        .HasColumnType("int");

                    b.Property<decimal?>("BU420ULDMengeProdu")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal?>("BU420ULDMengeStunden")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<int?>("BU437ULDKGMenge")
                        .HasColumnType("int");

                    b.Property<decimal?>("BU437ULDKGProdu")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal?>("BU437ULDKGStunden")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<int?>("BU437ULDMengeMenge")
                        .HasColumnType("int");

                    b.Property<decimal?>("BU437ULDMengeProdu")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal?>("BU437ULDMengeStunden")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<int?>("BUAbfertigerIst")
                        .HasColumnType("int");

                    b.Property<int?>("BUAbfertigerKrank")
                        .HasColumnType("int");

                    b.Property<int?>("BUAbfertigerSoll")
                        .HasColumnType("int");

                    b.Property<decimal?>("BUAbfertigerZusatz")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<int?>("BUPalettiererIst")
                        .HasColumnType("int");

                    b.Property<int?>("BUPalettiererKrank")
                        .HasColumnType("int");

                    b.Property<int?>("BUPalettiererSoll")
                        .HasColumnType("int");

                    b.Property<decimal?>("BUPalettiererZusatz")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<int?>("BUSupervisorIst")
                        .HasColumnType("int");

                    b.Property<int?>("BUSupervisorKrank")
                        .HasColumnType("int");

                    b.Property<int?>("BUSupervisorSoll")
                        .HasColumnType("int");

                    b.Property<decimal?>("BUSupervisorZusatz")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<int?>("BUTeamleadIst")
                        .HasColumnType("int");

                    b.Property<int?>("BUTeamleadKrank")
                        .HasColumnType("int");

                    b.Property<int?>("BUTeamleadSoll")
                        .HasColumnType("int");

                    b.Property<decimal?>("BUTeamleadZusatz")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<int?>("CDSdgrBD420")
                        .HasColumnType("int");

                    b.Property<int?>("CDSdgrBD437")
                        .HasColumnType("int");

                    b.Property<int?>("CDSdgrBD451")
                        .HasColumnType("int");

                    b.Property<int?>("CDSdgrBU320")
                        .HasColumnType("int");

                    b.Property<int?>("CDSdgrBU420")
                        .HasColumnType("int");

                    b.Property<int?>("CDSdgrBU437")
                        .HasColumnType("int");

                    b.Property<int?>("CDSstandardBD420")
                        .HasColumnType("int");

                    b.Property<int?>("CDSstandardBD437")
                        .HasColumnType("int");

                    b.Property<int?>("CDSstandardBD451")
                        .HasColumnType("int");

                    b.Property<int?>("CDSstandardBU320")
                        .HasColumnType("int");

                    b.Property<int?>("CDSstandardBU420")
                        .HasColumnType("int");

                    b.Property<int?>("CDSstandardBU437")
                        .HasColumnType("int");

                    b.Property<int?>("DutymanagerIst")
                        .HasColumnType("int");

                    b.Property<int?>("DutymanagerKrank")
                        .HasColumnType("int");

                    b.Property<int?>("DutymanagerSoll")
                        .HasColumnType("int");

                    b.Property<decimal?>("DutymanagerZusatz")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<string>("HDO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LeihscannerBD420")
                        .HasColumnType("int");

                    b.Property<int?>("LeihscannerBD437")
                        .HasColumnType("int");

                    b.Property<int?>("LeihscannerBD451")
                        .HasColumnType("int");

                    b.Property<int?>("LeihscannerBU320")
                        .HasColumnType("int");

                    b.Property<int?>("LeihscannerBU420")
                        .HasColumnType("int");

                    b.Property<int?>("LeihscannerBU437")
                        .HasColumnType("int");

                    b.Property<int?>("LeihstaplerBD420")
                        .HasColumnType("int");

                    b.Property<int?>("LeihstaplerBD437")
                        .HasColumnType("int");

                    b.Property<int?>("LeihstaplerBD451")
                        .HasColumnType("int");

                    b.Property<int?>("LeihstaplerBU320")
                        .HasColumnType("int");

                    b.Property<int?>("LeihstaplerBU420")
                        .HasColumnType("int");

                    b.Property<int?>("LeihstaplerBU437")
                        .HasColumnType("int");

                    b.Property<string>("SchichtleiterLF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchichtleiterPT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TransportDIRMenge")
                        .HasColumnType("int");

                    b.Property<decimal?>("TransportDIRProdu")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal?>("TransportDIRStunden")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<int?>("TransportHRLMenge")
                        .HasColumnType("int");

                    b.Property<decimal?>("TransportHRLProdu")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal?>("TransportHRLStunden")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<int?>("TransportPerkoMenge")
                        .HasColumnType("int");

                    b.Property<decimal?>("TransportPerkoProdu")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal?>("TransportPerkoStunden")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<int?>("TransportQuerMenge")
                        .HasColumnType("int");

                    b.Property<decimal?>("TransportQuerProdu")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal?>("TransportQuerStunden")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<DateTime>("abgeschlossenam")
                        .HasColumnType("datetime2");

                    b.Property<string>("abgeschlossenvon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("erstelltam")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("erstelltvon")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("freigegebenam")
                        .HasColumnType("datetime2");

                    b.Property<string>("freigegebenvon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("istabgeschlossen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("istfreigegeben")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("schichtbeurteilung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("schichttyp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("schichttyp_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("zuletztbearbeitetam")
                        .HasColumnType("datetime2");

                    b.Property<string>("zuletztbearbeitetvon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Overview");
                });

            modelBuilder.Entity("FACLSchichtbericht.Models.PersonalplanModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bemerkung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bereich")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BerichtBD420_ID")
                        .HasColumnType("int");

                    b.Property<int?>("BerichtBD451_ID")
                        .HasColumnType("int");

                    b.Property<int?>("BerichtBU320_ID")
                        .HasColumnType("int");

                    b.Property<int?>("BerichtBU420_ID")
                        .HasColumnType("int");

                    b.Property<string>("Brandschutzhelfer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Einsatzals")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ersthelfer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gewerk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jobtitel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nachname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PK")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vorname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("anwesend")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("datumgeplant")
                        .HasColumnType("datetime2");

                    b.Property<string>("erstelltam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("erstelltvon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("istabgeschlossen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mehrarbeitgenehmight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("schichttyp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("zuletztbearbeitetam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("zuletztbearbeitetvon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Personalplan");
                });

            modelBuilder.Entity("FACLSchichtbericht.Models.SchichttypModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bezeichnung")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Schichttyp");
                });
#pragma warning restore 612, 618
        }
    }
}
