// <auto-generated />
using System;
using FACLSchichtbericht.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FACLSchichtbericht.Migrations
{
    [DbContext(typeof(FACL_DB_DevContext))]
    [Migration("20210319080245_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FACLSchichtbericht.Models.BerichtBD420", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AbfertigerIst")
                        .HasColumnType("int");

                    b.Property<int?>("AbfertigerKrank")
                        .HasColumnType("int");

                    b.Property<int?>("AbfertigerSoll")
                        .HasColumnType("int");

                    b.Property<int?>("AbfertigerZusatz")
                        .HasColumnType("int");

                    b.Property<string>("Arbeitunsfall")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AufbauerIst")
                        .HasColumnType("int");

                    b.Property<int?>("AufbauerKrank")
                        .HasColumnType("int");

                    b.Property<int?>("AufbauerSoll")
                        .HasColumnType("int");

                    b.Property<int?>("AufbauerZusatz")
                        .HasColumnType("int");

                    b.Property<int?>("AwaitingBulk")
                        .HasColumnType("int");

                    b.Property<int?>("AwaitingBulkFast")
                        .HasColumnType("int");

                    b.Property<int?>("AwaitingLCC")
                        .HasColumnType("int");

                    b.Property<int?>("AwaitingLCCFast")
                        .HasColumnType("int");

                    b.Property<int?>("BDStartBulk")
                        .HasColumnType("int");

                    b.Property<int?>("BDStartBulkFast")
                        .HasColumnType("int");

                    b.Property<int?>("BDStartLCC")
                        .HasColumnType("int");

                    b.Property<int?>("BDStartLCCFast")
                        .HasColumnType("int");

                    b.Property<int?>("BulkMengeMaStunden")
                        .HasColumnType("int");

                    b.Property<int?>("BulkMengeMenge")
                        .HasColumnType("int");

                    b.Property<int?>("BulkMengeProdu")
                        .HasColumnType("int");

                    b.Property<int?>("CDSDGR")
                        .HasColumnType("int");

                    b.Property<int?>("CDSStandard")
                        .HasColumnType("int");

                    b.Property<string>("Checker1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Checker2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Checker3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Checker4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Checker5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CheckerIst")
                        .HasColumnType("int");

                    b.Property<int?>("CheckerKrank")
                        .HasColumnType("int");

                    b.Property<int?>("CheckerSoll")
                        .HasColumnType("int");

                    b.Property<int?>("CheckerZusatz")
                        .HasColumnType("int");

                    b.Property<string>("DGRChecker1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DGRChecker2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Frachtsicherung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HalBulk")
                        .HasColumnType("int");

                    b.Property<int?>("HalBulkFast")
                        .HasColumnType("int");

                    b.Property<int?>("HalLCC")
                        .HasColumnType("int");

                    b.Property<int?>("HalLCCFast")
                        .HasColumnType("int");

                    b.Property<string>("LagerdatenChecker")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Leihscanner")
                        .HasColumnType("int");

                    b.Property<int?>("Leihstapler")
                        .HasColumnType("int");

                    b.Property<int?>("PbEiBulk")
                        .HasColumnType("int");

                    b.Property<int?>("PbEiLCC")
                        .HasColumnType("int");

                    b.Property<int?>("PbEiLoco")
                        .HasColumnType("int");

                    b.Property<int?>("PbMiBulk")
                        .HasColumnType("int");

                    b.Property<int?>("PbMiLCC")
                        .HasColumnType("int");

                    b.Property<int?>("PbMiLoco")
                        .HasColumnType("int");

                    b.Property<int?>("Pending")
                        .HasColumnType("int");

                    b.Property<int?>("PendingBulk")
                        .HasColumnType("int");

                    b.Property<int?>("PendingBulkFast")
                        .HasColumnType("int");

                    b.Property<int?>("PendingLCCFast")
                        .HasColumnType("int");

                    b.Property<string>("QundS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchichtleiterLCAG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Supervisor1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Supervisor2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SupervisorIst")
                        .HasColumnType("int");

                    b.Property<int?>("SupervisorKrank")
                        .HasColumnType("int");

                    b.Property<int?>("SupervisorSoll")
                        .HasColumnType("int");

                    b.Property<int?>("SupervisorZusatz")
                        .HasColumnType("int");

                    b.Property<int?>("ULDKG")
                        .HasColumnType("int");

                    b.Property<int?>("ULDKGMAStunden")
                        .HasColumnType("int");

                    b.Property<int?>("ULDKGProdu")
                        .HasColumnType("int");

                    b.Property<int?>("ULDMengeMAStunden")
                        .HasColumnType("int");

                    b.Property<int?>("ULDMengeMenge")
                        .HasColumnType("int");

                    b.Property<int?>("ULDMengeProdu")
                        .HasColumnType("int");

                    b.Property<string>("VormannLCAG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("abgeschlossenam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("abgeschlossenvon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("erstelltam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("erstelltvon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("freigegebenam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("freigegebenvon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("istabgeschlossen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("istfreigegeben")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("schichtbeginn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("schichtbeurteilung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("schichtdatum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("schichtende")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("schichttyp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("zuletztbearbeitetam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("zuletztbearbeitetvon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("BerichtBD420");
                });
#pragma warning restore 612, 618
        }
    }
}
